package com.data_management;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Reads patient data files generated by the simulator's file output strategy.
 * Expected line format:
 * Patient ID: 1, Timestamp: 1714376789050, Label: Saturation, Data: 95%
 */
public class FileDataReader implements DataReader {

    private final Path outputDirectory;

    /**
     * Creates a reader for the simulator output directory.
     *
     * @param outputDirectory path to the directory passed to --output file:<output_dir>
     */
    public FileDataReader(String outputDirectory) {
        this(Paths.get(outputDirectory));
    }

    /**
     * Creates a reader for the simulator output directory.
     *
     * @param outputDirectory path to the directory passed to --output file:<output_dir>
     */
    public FileDataReader(Path outputDirectory) {
        this.outputDirectory = outputDirectory;
    }

    /**
     * Reads all simulator-generated text files and stores the parsed records.
     *
     * @param dataStorage the storage where parsed records will be stored
     * @throws IOException if the directory or a line cannot be read or parsed
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {

        if (!Files.isDirectory(outputDirectory)) {
            throw new IOException("Output path is not a directory: " + outputDirectory);
        }

        try (Stream<Path> paths = Files.list(outputDirectory)) {
            List<Path> dataFiles = paths
                    .filter(Files::isRegularFile)
                    .filter(path -> path.getFileName().toString().endsWith(".txt"))
                    .sorted()
                    .collect(Collectors.toList());

            for (Path dataFile : dataFiles) {
                readFile(dataFile, dataStorage);
            }
        }
    }

    private void readFile(Path dataFile, DataStorage dataStorage) throws IOException {

        try (BufferedReader reader = Files.newBufferedReader(dataFile)) {
            String line;
            int lineNumber = 0;

            while ((line = reader.readLine()) != null) {
                lineNumber++;
                if (!line.trim().isEmpty()) {
                    parseLine(line, dataFile, lineNumber, dataStorage);
                }
            }
        }
    }

    private void parseLine(String line, Path dataFile, int lineNumber, DataStorage dataStorage) throws IOException {
        try {
            PatientRecord record = PatientDataParser.parse(line);

            dataStorage.addPatientData(
                    record.getPatientId(),
                    record.getMeasurementValue(),
                    record.getRecordType(),
                    record.getTimestamp());

        } catch (IOException exception) {
            throw new IOException(
                    "Invalid patient data line in " + dataFile + " at line " + lineNumber + ": " + line, exception);
        }
    }

}
