package com.data_management;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Reads patient data files generated by the simulator's file output strategy.
 * Expected line format:
 * Patient ID: 1, Timestamp: 1714376789050, Label: Saturation, Data: 95%
 */
public class FileDataReader implements DataReader {

    public static final double ALERT_TRIGGERED_VALUE = 1.0;
    public static final double ALERT_RESOLVED_VALUE = 0.0;

    private static final Pattern OUTPUT_LINE_PATTERN = Pattern.compile(
            "^Patient ID:\\s*(\\d+),\\s*Timestamp:\\s*(\\d+),\\s*Label:\\s*([^,]+),\\s*Data:\\s*(.+)$");

    private final Path outputDirectory;

    /**
     * Creates a reader for the simulator output directory.
     *
     * @param outputDirectory path to the directory passed to --output file:<output_dir>
     */
    public FileDataReader(String outputDirectory) {
        this(Paths.get(outputDirectory));
    }

    /**
     * Creates a reader for the simulator output directory.
     *
     * @param outputDirectory path to the directory passed to --output file:<output_dir>
     */
    public FileDataReader(Path outputDirectory) {
        this.outputDirectory = outputDirectory;
    }

    /**
     * Reads all simulator-generated text files and stores the parsed records.
     *
     * @param dataStorage the storage where parsed records will be stored
     * @throws IOException if the directory or a line cannot be read or parsed
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {

        if (!Files.isDirectory(outputDirectory)) {
            throw new IOException("Output path is not a directory: " + outputDirectory);
        }

        try (Stream<Path> paths = Files.list(outputDirectory)) {
            List<Path> dataFiles = paths
                    .filter(Files::isRegularFile)
                    .filter(path -> path.getFileName().toString().endsWith(".txt"))
                    .sorted()
                    .collect(Collectors.toList());

            for (Path dataFile : dataFiles) {
                readFile(dataFile, dataStorage);
            }
        }
    }

    private void readFile(Path dataFile, DataStorage dataStorage) throws IOException {

        try (BufferedReader reader = Files.newBufferedReader(dataFile)) {
            String line;
            int lineNumber = 0;

            while ((line = reader.readLine()) != null) {
                lineNumber++;
                if (!line.trim().isEmpty()) {
                    parseLine(line, dataFile, lineNumber, dataStorage);
                }
            }
        }
    }

    private void parseLine(String line, Path dataFile, int lineNumber, DataStorage dataStorage) throws IOException {

        Matcher matcher = OUTPUT_LINE_PATTERN.matcher(line.trim());

        if (!matcher.matches()) {
            throw new IOException("Invalid patient data line in " + dataFile + " at line " + lineNumber + ": " + line);
        }

        int patientId = Integer.parseInt(matcher.group(1));
        long timestamp = Long.parseLong(matcher.group(2));
        String recordType = matcher.group(3).trim();
        double measurementValue = parseMeasurementValue(matcher.group(4).trim(), dataFile, lineNumber);

        dataStorage.addPatientData(patientId, measurementValue, recordType, timestamp);
    }

    private double parseMeasurementValue(String rawValue, Path dataFile, int lineNumber) throws IOException {
        
        String normalizedValue = rawValue.trim();

        if (normalizedValue.endsWith("%")) {
            normalizedValue = normalizedValue.substring(0, normalizedValue.length() - 1).trim();
        }

        if (normalizedValue.equalsIgnoreCase("triggered")) {
            return ALERT_TRIGGERED_VALUE;
        }

        if (normalizedValue.equalsIgnoreCase("resolved") || normalizedValue.equalsIgnoreCase("untriggered")) {
            return ALERT_RESOLVED_VALUE;
        }

        try {
            return Double.parseDouble(normalizedValue);
        } catch (NumberFormatException exception) {
            throw new IOException(
                    "Invalid numeric value in " + dataFile + " at line " + lineNumber + ": " + rawValue,
                    exception);
        }
    }
}
